name: Build the NuGet-package and publish it to nuget.org
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  verify-quality:
    name: Verify quality
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Verify quality
        run: dotnet test code/Eshva.Caching.Nats.slnx --configuration Release --logger:"xunit;LogFilePath=test_result.xml" --results-directory .
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "./**/test_result.xml"
          check_name: "Test results"
          action_fail: true
  build-and-publish:
    name: Build the NuGet-package and publish it to nuget.org
    needs: verify-quality
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build sources
        run: dotnet build code/solutions/Eshva.Testing.OutOfProcessDeployments.Nats.csproj --configuration Release
      - name: Pack the NuGet-package
        run: dotnet pack code/solutions/Eshva.Testing.OutOfProcessDeployments.Nats.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish the NuGet-package to nuget.org
        run: dotnet nuget push Eshva.Caching.Nats.${VERSION}.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
